# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsqitch" do
  name "gsqitch"
  desc "A Go port of the excellent Sqitch database change management application."
  homepage "https://github.com/mvgrimes/gsqitch"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsqitch"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_x86_64.tar.gz"
      sha256 "3019981ba225ebd0571a1061a4f1a6dddcc615a2522fcdcb6bfd0e02227c98a6"
    end
    on_arm do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_arm64.tar.gz"
      sha256 "9800f1a301993ac2f4f18fa6ad74cf625fdd8670a8f1be86baed80c089a3e9bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_x86_64.tar.gz"
      sha256 "c7e4133bab05848456bccf7e3b86c996f60508995fd6e1d608e6cc0894c133c6"
    end
    on_arm do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_arm64.tar.gz"
      sha256 "fece58eb7d5016cb21b6b4bbf34ce6edf82dee393f8ac004a383ce49be8c306a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lm"]
    end
  end

  # No zap stanza required
end
