# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsqitch" do
  name "gsqitch"
  desc "Go port of the excellent Sqitch database change management application"
  homepage "https://github.com/mvgrimes/gsqitch"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsqitch"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_x86_64.tar.gz"
      sha256 "c5701f13e82dee3d07c7b42e5c7c793c4197ddd0730aa6e8431804309b1bed8d"
    end
    on_arm do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_arm64.tar.gz"
      sha256 "40ec31e728222b836a795cf13eaed1885b9f7dd679b3116b1fc2ed7529dca7c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_x86_64.tar.gz"
      sha256 "624621cd099678747907caf3b9aa3f697a9a92aad1310894c70a0e080790831c"
    end
    on_arm do
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_arm64.tar.gz"
      sha256 "77efb526ef56a0b73de1f2d8fcc97d376f35f8edbaa464f9409dc9c0ffc95c57"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gsqitch"] if OS.mac?
  end

  # No zap stanza required
end
