# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsqitch" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "f7e6a8d30a848b4bc3d7d2c1b6cfb1e6ff2396ea159f40ad9a92f66615113e2d"
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6a932e16bf8d0c2cfc12a38d3289589d2febde0677492cab9c2a0cfd397cfa3d"
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c22f97d39ee7fc35da9da312070df792736c2d0c8d225ac76fd44e36a459d221"
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bfe3c03dee3c348a880fab87ec1ff19c5f23a627ac77befad7fd3c2ab09b3557"
      url "https://github.com/mvgrimes/gsqitch/releases/download/#{version}/gsqitch_Linux_arm64.tar.gz"
    end
  end

  name "gsqitch"
  desc "Go port of the excellent Sqitch database change management application"
  homepage "https://github.com/mvgrimes/gsqitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsqitch"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gsqitch"] if OS.mac?
  end

  # No zap stanza required

end
