# This file was generated by GoReleaser. DO NOT EDIT.
cask "hb-test" do
  name "hb-test"
  desc ""
  homepage ""
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hb-test"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_x86_64.tar.gz"
      sha256 "856252a0476da3d238f8dfe473a81f386c92afc262d4c6860c5c57e378b0beac"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_arm64.tar.gz"
      sha256 "a98e38df3a8f4c7b726dcfc59025b2149acfd5808bc265e9968d402b3bc28324"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_x86_64.tar.gz"
      sha256 "8347a43c41b84b6cb223d5c4c0889b5f18934ad9e39ce883f117b1c47fafbb6e"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_arm64.tar.gz"
      sha256 "a9ddb0209dc907bee25772f16ed52c71baadfdd9dfc85e4d27fcc7f435a24306"
    end
  end

  # No zap stanza required
end
