# This file was generated by GoReleaser. DO NOT EDIT.
cask "hb-test" do
  name "hb-test"
  desc ""
  homepage ""
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hb-test"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_x86_64.tar.gz"
      sha256 "fb57d49ace5872457be7e853dc7482add03eb2c3312f596a229d0a8c94cbf3aa"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_arm64.tar.gz"
      sha256 "553bd819314bc2f0f3b92f21e3bbeee0aa975ed24a5cf60de38423365b295012"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_x86_64.tar.gz"
      sha256 "cec3f0159307a2cb302c74592c5524be6a3a602d9b655e59d18dbb64e13d4f68"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_arm64.tar.gz"
      sha256 "a2f5d353464842db6886f83e950550873ff70913b882ad2755a9bca4c7f6ff22"
    end
  end

  # No zap stanza required
end
