# This file was generated by GoReleaser. DO NOT EDIT.
cask "immich-aa" do
  name "immich-aa"
  desc "Populate an Immich album with a random selection of photos from around this day in prior years"
  homepage "https://github.com/mvgrimes/immich-aa"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "immich-aa"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/immich-aa/releases/download/#{version}/immich-aa_Darwin_x86_64.tar.gz"
      sha256 "bfbb4de7a9d796f8f99e2ef6c51947f246f5b843d506f3af0f00393c70e3ac99"
    end
    on_arm do
      url "https://github.com/mvgrimes/immich-aa/releases/download/#{version}/immich-aa_Darwin_arm64.tar.gz"
      sha256 "800dd896020016d64b8d373e060e53d3bc286819ef97417cda337398e42fe22c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/immich-aa/releases/download/#{version}/immich-aa_Linux_x86_64.tar.gz"
      sha256 "ed5b78401244bebdc72c0d3e4a3a6755c6c3743494dc8e3ffee002ed8fe67b42"
    end
    on_arm do
      url "https://github.com/mvgrimes/immich-aa/releases/download/#{version}/immich-aa_Linux_arm64.tar.gz"
      sha256 "8bdc7593b4a69294b772e40f74aa9d91befa36958bef77f32b3837160c8c4940"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/immich-aa"] if OS.mac?
  end

  # No zap stanza required
end
