# This file was generated by GoReleaser. DO NOT EDIT.
cask "lm" do
  name "lm"
  desc ""
  homepage ""
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lm"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_x86_64.tar.gz"
      sha256 "816af084c7b6578658c024b6acb53ee05d083a00cdbe20b5862a714a6f4777b3"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_arm64.tar.gz"
      sha256 "26889185660c47a09750c77fc1983be48411b3402f04d17c138e328c03529f30"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_x86_64.tar.gz"
      sha256 "1fa21e39cafe2fae86b5cbbe001913658edeff02aa9d7d7064012b483c656f06"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_arm64.tar.gz"
      sha256 "361215204f4923e095aa4e0fac3e26609c26dccd9300c590f3b3ff06434befd9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lm"]
    end
  end

  # No zap stanza required
end
