# This file was generated by GoReleaser. DO NOT EDIT.
cask "lm" do
  name "lm"
  desc ""
  homepage ""
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lm"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_x86_64.tar.gz"
      sha256 "1d82e604b4f60d867045b4def5f8f73e067c04cc0fa58ac828b4b694eb7fd110"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_arm64.tar.gz"
      sha256 "6218f422a75f8817730c1b4cba00a589614196686134fac981b07371f11a1906"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_x86_64.tar.gz"
      sha256 "d080610b066f8f12677821cd454eb1c4218c8b4300a519cbb472cf619d31cd2d"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_arm64.tar.gz"
      sha256 "164c754ff97650eb741d2fa707dc1410f8e30a90c98130f02b9283e4be117963"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lm"]
    end
  end

  # No zap stanza required
end
