# This file was generated by GoReleaser. DO NOT EDIT.
cask "lm" do
  name "lm"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lm"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_x86_64.tar.gz"
      sha256 "81375075cd8e137824bd7483770371ee061ffee4983532e7053d6a47c5e61600"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Darwin_arm64.tar.gz"
      sha256 "e4b7b378c75f8fe31a8dd3b52665b3bc3413317bc061e7b903c88443f4359b9d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_x86_64.tar.gz"
      sha256 "a3a6d3c8e1a62128dd34f0734f07be06a9dccb17a446db6fa2e3c81ce0a502cd"
    end
    on_arm do
      url "https://github.com/mvgrimes/lm/releases/download/#{version}/lm_Linux_arm64.tar.gz"
      sha256 "d35d183ce88ce74746501c86238ab5400e8115b2b7e326039f3cb08c932bb049"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lm"]
    end
  end

  # No zap stanza required
end
