# This file was generated by GoReleaser. DO NOT EDIT.
cask "mytui" do
  name "mytui"
  desc ""
  homepage ""
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mytui"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Darwin_x86_64.tar.gz"
      sha256 "a786fcb59f589e325b433334a2f70bf1f6d7b046ca8b8e2f2163a7b46b0c320d"
    end
    on_arm do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Darwin_arm64.tar.gz"
      sha256 "5b7da4ce40f0c385e932d75e53efbc66c51b52627cee9d3604c826807edf2678"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Linux_x86_64.tar.gz"
      sha256 "1f2a9fb198e8f279b9a801f57d18906bbfc2f221aa475e217ac73d2e4eb4ee68"
    end
    on_arm do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Linux_arm64.tar.gz"
      sha256 "52b06f468e37f9ba34445f8d0b0937dccb81eab6ccc80894adde16b2c42782a7"
    end
  end

  # No zap stanza required
end
