# This file was generated by GoReleaser. DO NOT EDIT.
cask "mytui" do
  name "mytui"
  desc ""
  homepage ""
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mytui"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Darwin_x86_64.tar.gz"
      sha256 "afaf16fef9025a350c663afe4fcc6ff66ec240af635995784945e007340ed715"
    end
    on_arm do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Darwin_arm64.tar.gz"
      sha256 "a325b381f305eed6adf344cd496ed0edfc2904bc4ddbe1b4b027d456c09132f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Linux_x86_64.tar.gz"
      sha256 "1818be80c0c6c334f374a57d8edb887935b40cfd88788328295409986fe49ab7"
    end
    on_arm do
      url "https://github.com/mvgrimes/mytui/releases/download/#{version}/mytui_Linux_arm64.tar.gz"
      sha256 "6e5f243a52d5c7f886389b6cc022dabc2df15b2b232b00518a91585715658ba4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mytui"]
    end
  end

  # No zap stanza required
end
