# This file was generated by GoReleaser. DO NOT EDIT.
cask "mytui" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "8f83cf114b0d2eed49dc434613b9d113298dabcef9947f6074d80ddc8f908b04"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3c7b5e3267339720fc536ccc9e0ff59881576fa3242e20f5a0810e3f6752e865"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d8044840008aacbd777c7125f47857f8a2a9533877ed9d6a1aa8f734a245988"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "47d044ae2896368590c0e6290ce68e87be3e6a177f142e027a83da7ec2db6e37"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_arm64.tar.gz"
    end
  end

  name "mytui"
  desc "Simple ticket tracker"
  homepage "https://github.com/mvgrimes/ticket-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mytui"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tk"] if OS.mac?
  end

  # No zap stanza required

end
