# This file was generated by GoReleaser. DO NOT EDIT.
cask "podman-pretty" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "4e187f5862f68342980445a6bc27e2665c4386b07a1f5fd539c85539ff8261e4"
      url "https://github.com/mvgrimes/podman-pretty/releases/download/#{version}/podman-pretty_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e2f0efffc47df8de7efee40885c1d5817ed8a9c8895065e79ae21ce35e1f020"
      url "https://github.com/mvgrimes/podman-pretty/releases/download/#{version}/podman-pretty_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a908a6a30b11381e16112a9d4be61052af816cd6e63b03239cacb497d104414e"
      url "https://github.com/mvgrimes/podman-pretty/releases/download/#{version}/podman-pretty_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e4632114e08fd0022e1c4e7d9b50210abfdbece3518c93cbc020e9cb234d894"
      url "https://github.com/mvgrimes/podman-pretty/releases/download/#{version}/podman-pretty_Linux_x86_64.tar.gz"
    end
  end

  name "podman-pretty"
  desc "A simple CLI tool that prettifies log output by colorizing and tracking timing between steps."
  homepage "https://github.com/mvgrimes/podman-pretty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podman-pretty"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podman-pretty"] if OS.mac?
  end

  # No zap stanza required
end
