# This file was generated by GoReleaser. DO NOT EDIT.
cask "ticket-go" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "9132d4080bb8edd3f5426c8a805e9743bd1c5b598d30a18aca22d9be2ff18947"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3cc16c7684250bc86237b6fbd805cc7a7642129398449a4aab3708d2e40fa9b7"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c1a35ea0f8d6c4aabef31c63329796c32aadd2ef1181152ac55b0bc35b388d81"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e1374b9a75a638041f97e34d85dd0c4d6ba37cfce14db2f9ba515381fc3c710a"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_arm64.tar.gz"
    end
  end

  name "ticket-go"
  desc "Simple ticket tracker"
  homepage "https://github.com/mvgrimes/ticket-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tk"] if OS.mac?
  end

  # No zap stanza required

end
