# This file was generated by GoReleaser. DO NOT EDIT.
cask "ticket-go" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "b5bf4c3de6f7b291187cae38faff0b1b59119ff94b5574a2483fd4b459b0a110"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5f8de080884b12ac51b023da9951fd3bd1214354e477081a37e5a00c5daae86f"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4455f7cc953cb504578cee8dcca3f870162d2de1991ce22dc3a0ba3247b82ff5"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f4c46fdf794c864553d11d4809b056b71db06fc312502cee47abac93c1db0a29"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_arm64.tar.gz"
    end
  end

  name "ticket-go"
  desc "Simple ticket tracker"
  homepage "https://github.com/mvgrimes/ticket-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ticket-go"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tk"] if OS.mac?
  end

  # No zap stanza required

end
