# This file was generated by GoReleaser. DO NOT EDIT.
cask "ticket-go" do
  version "0.4.7"

  on_macos do
    on_intel do
      sha256 "d74bd46d6b4cf691d68f066339f8879950f05266061460e67b2f697d5932b309"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9935ee2b10df91e8f35f14c8489e7d552e32330d0b448f433ff9ae3ced157847"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1385eff368a76a93ad34b4f6c88dcccb282176b4c769cbd344cbc0e5a24f7058"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8fa39b57b77cb585a16e1c6cde39d1b1ec69bbf00f13e49a936a938d6043d9b8"
      url "https://github.com/mvgrimes/ticket-go/releases/download/#{version}/ticket-go_Linux_arm64.tar.gz"
    end
  end

  name "ticket-go"
  desc "Simple ticket tracker"
  homepage "https://github.com/mvgrimes/ticket-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tk"] if OS.mac?
  end

  # No zap stanza required

end
