# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmux" do
  version "0.2.5"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_x86_64.tar.gz"
      sha256 "cd04cc6c12096c995f2f8acc465c127d79ff72d45fa7c4bb898187b0b34cd33b"
    end
    on_arm do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_arm64.tar.gz"
      sha256 "0b0f9ce12e33ef52f933f76a7a96084f2152ba9b8eb63e11ccb8dc0c8b119a27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_x86_64.tar.gz"
      sha256 "5f7c4f2f5fc4cb9a955177bb0f8c4bb4b4709366b5c3d555fe471d32dfb39555"
    end
    on_arm do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_arm64.tar.gz"
      sha256 "0724278cb452f198da8ba077a28518e0982fb3e0aa6b3488488edbd0f1051f4f"
    end
  end

  name "xmux"
  desc "tmux session launcher and service monitor"
  homepage "https://github.com/mvgrimes/xmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmux"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmux"] if OS.mac?
  end

  # No zap stanza required

end
