# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmux" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_x86_64.tar.gz"
      sha256 "0b9487f1ac3a82e307b1ab1aa674aa7c384bde9e0127835838ef1f56b3b78aa7"
    end
    on_arm do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_arm64.tar.gz"
      sha256 "5379fa8b86c4b20386bb03fbf106f1ba5fdcf8b0052206b201ebb2a30b5e6754"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_x86_64.tar.gz"
      sha256 "1caf630b6a04bf4877a504b19b687a3eb5059c1c4b5da841c641cc39277225e8"
    end
    on_arm do
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_arm64.tar.gz"
      sha256 "2fe5b077cad1e2e67f766856fafd6836cea692ebb5dc329731d6bf2f6f7192d5"
    end
  end

  name "xmux"
  desc "tmux session launcher and service monitor"
  homepage "https://github.com/mvgrimes/xmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmux"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmux"] if OS.mac?
  end

  # No zap stanza required

end
