# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmux" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "acd9f31985333b31b90694f582c74c2325dacc4d67b37c4924048f1bb2ab77e1"
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c8cac385ad6a955cbcdf537c6288d9739e3741c52af8056c1f43d95b908d4af2"
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d50a85e189cce69d090a139298286702f996a588ebea6e2b525b9cd9c8abd885"
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f4405d2fde267e66f5fc84313aac322400f429d9388bd5788d837b4906bfee1e"
      url "https://github.com/mvgrimes/xmux/releases/download/#{version}/xmux_Linux_arm64.tar.gz"
    end
  end

  name "xmux"
  desc "tmux session launcher and service monitor"
  homepage "https://github.com/mvgrimes/xmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmux"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmux"] if OS.mac?
  end

  # No zap stanza required

end
